# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Discover and run all tests using unittest module
      run: |
        python3 -m unittest tests/test_proximity_alert.py
    - name: Run mypy strict type checking
      run: |
        python -m pip install --upgrade pip
        python -m pip install mypy
        mypy --strict proximity_alert.py
        mypy --strict tests/test_proximity_alert.py
